In [1]:
import numpy as np

In [2]:
my_list = [1,2,3]

In [3]:
my_list

[1, 2, 3]

In [4]:
np.array(my_list)

array([1, 2, 3])

In [5]:
my_matrix = [[1,2,3],[4,5,6],[7,8,9]]

In [6]:
my_matrix

[[1, 2, 3], [4, 5, 6], [7, 8, 9]]

In [7]:
np.array(my_matrix)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

# arange

In [9]:
np.arange(0,11)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [10]:
np.arange(0,11,3)

array([0, 3, 6, 9])

# zeros and ones

In [11]:
np.zeros(3)

array([0., 0., 0.])

In [14]:
np.zeros((5,5))

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [15]:
np.ones(3)

array([1., 1., 1.])

In [16]:
np.ones((3,3))

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

# linspace 

return evenly spaced numbers over a specified interval

In [20]:
np.linspace(0,10,4)

array([ 0.        ,  3.33333333,  6.66666667, 10.        ])

In [21]:
np.linspace(0,10,50)

array([ 0.        ,  0.20408163,  0.40816327,  0.6122449 ,  0.81632653,
        1.02040816,  1.2244898 ,  1.42857143,  1.63265306,  1.83673469,
        2.04081633,  2.24489796,  2.44897959,  2.65306122,  2.85714286,
        3.06122449,  3.26530612,  3.46938776,  3.67346939,  3.87755102,
        4.08163265,  4.28571429,  4.48979592,  4.69387755,  4.89795918,
        5.10204082,  5.30612245,  5.51020408,  5.71428571,  5.91836735,
        6.12244898,  6.32653061,  6.53061224,  6.73469388,  6.93877551,
        7.14285714,  7.34693878,  7.55102041,  7.75510204,  7.95918367,
        8.16326531,  8.36734694,  8.57142857,  8.7755102 ,  8.97959184,
        9.18367347,  9.3877551 ,  9.59183673,  9.79591837, 10.        ])

# eye

create an identity matrix

In [22]:
np.eye(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [23]:
np.eye(2)

array([[1., 0.],
       [0., 1.]])

# rand

In [24]:
np.random.rand(2)

array([0.69347251, 0.46511244])

In [25]:
np.random.rand(4)

array([0.63649182, 0.0169027 , 0.32740258, 0.95223769])

In [26]:
np.random.rand(2,2)

array([[0.00499756, 0.29617645],
       [0.71167832, 0.62325501]])

# randint 
random integers from low to high

In [27]:
np.random.randint(1,100)

26

In [30]:
np.random.randint(1,100,20)

array([ 7, 67, 87, 84, 97,  7, 52, 35, 97, 26, 39, 57, 22, 80, 55, 92, 32,
       35, 17, 53])

# array attributes and methods

In [31]:
arr = np.arange(25)
ranarr = np.random.randint(0,100,10)

In [32]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24])

In [33]:
ranarr

array([ 5,  3, 61, 33, 96, 78, 75, 33, 65, 39])

# reshape

In [34]:
arr.reshape(5,5)

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

# max, min, argmax, argmin

In [35]:
ranarr

array([ 5,  3, 61, 33, 96, 78, 75, 33, 65, 39])

In [37]:
ranarr.max()

96

In [38]:
ranarr.min()

3

In [39]:
ranarr.argmax()

4

In [40]:
ranarr.argmin()

1

# shape

In [41]:
arr.shape

(25,)

In [46]:
arr.reshape(5,5)

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [47]:
ranarr.shape

(10,)

In [48]:
arr.reshape(5,5)

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [49]:
arr.reshape(25,1).shape

(25, 1)

In [50]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24])

In [51]:
arr.reshape(5,5).shape

(5, 5)

In [52]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24])

In [53]:
arr.dtype

dtype('int32')

In [54]:
ranarr.dtype

dtype('int32')

# Numpy
# indexing 
# and
# selection

In [55]:
arr = np.arange(0,11)

In [58]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

# bracket indexing and selection

In [59]:
arr[8]

8

In [60]:
arr[1:5]

array([1, 2, 3, 4])

In [61]:
arr[0:5]

array([0, 1, 2, 3, 4])

# brodcasting

In [62]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [65]:
arr[0:5] = 11

In [66]:
arr

array([11, 11, 11, 11, 11,  5,  6,  7,  8,  9, 10])

In [73]:
arr = np.arange(0,10)

In [75]:
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [76]:
slice_of_arr = arr[0:6]

In [77]:
slice_of_arr

array([0, 1, 2, 3, 4, 5])

In [78]:
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [79]:
arr_copy = arr.copy()

In [80]:
arr_copy

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [88]:
arr_copy = 10

In [89]:
arr_copy

10

In [90]:
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

# indexing a 2d array (matrix)

 format is arr_2d[row][col] or arr_2d[row,col]

In [92]:
arr_2d = np.array(([2,4,6],[5,10,15],[7,14,21]))

In [94]:
arr_2d

array([[ 2,  4,  6],
       [ 5, 10, 15],
       [ 7, 14, 21]])

In [95]:
arr_2d[1]

array([ 5, 10, 15])

In [96]:
arr_2d[2][1]

14

In [97]:
arr_2d[1,2]

15

In [98]:
arr_2d[:2,1:]

array([[ 4,  6],
       [10, 15]])

In [100]:
arr_2d[:2,:1]

array([[2],
       [5]])

# fancy indexing

In [102]:
arr1 = np.arange(0,10)

In [103]:
arr1

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [104]:
arr1 > 5

array([False, False, False, False, False, False,  True,  True,  True,
        True])

In [105]:
bool_arr = arr1 > 5

In [106]:
bool_arr

array([False, False, False, False, False, False,  True,  True,  True,
        True])

In [107]:
arr1[bool_arr]

array([6, 7, 8, 9])

In [108]:
arr1[arr1>5]

array([6, 7, 8, 9])

In [109]:
arr1[arr1<3]

array([0, 1, 2])

In [114]:
arr3d = np.arange(50).reshape(5,10)

In [115]:
arr3d

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49]])

In [116]:
arr3d[1:3]

array([[10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29]])

In [117]:
arr3d[1:3,3:5]

array([[13, 14],
       [23, 24]])

In [118]:
arr4d = np.ones((10,10))

In [119]:
arr4d

array([[1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.]])

In [120]:
arr_length = arr4d.shape[1]

In [124]:
for i in range(arr_length):
    arr4d[i] = i +1
arr4d

array([[ 1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.],
       [ 2.,  2.,  2.,  2.,  2.,  2.,  2.,  2.,  2.,  2.],
       [ 3.,  3.,  3.,  3.,  3.,  3.,  3.,  3.,  3.,  3.],
       [ 4.,  4.,  4.,  4.,  4.,  4.,  4.,  4.,  4.,  4.],
       [ 5.,  5.,  5.,  5.,  5.,  5.,  5.,  5.,  5.,  5.],
       [ 6.,  6.,  6.,  6.,  6.,  6.,  6.,  6.,  6.,  6.],
       [ 7.,  7.,  7.,  7.,  7.,  7.,  7.,  7.,  7.,  7.],
       [ 8.,  8.,  8.,  8.,  8.,  8.,  8.,  8.,  8.,  8.],
       [ 9.,  9.,  9.,  9.,  9.,  9.,  9.,  9.,  9.,  9.],
       [10., 10., 10., 10., 10., 10., 10., 10., 10., 10.]])

In [125]:
arr4d[[2,4,6,8]]

array([[3., 3., 3., 3., 3., 3., 3., 3., 3., 3.],
       [5., 5., 5., 5., 5., 5., 5., 5., 5., 5.],
       [7., 7., 7., 7., 7., 7., 7., 7., 7., 7.],
       [9., 9., 9., 9., 9., 9., 9., 9., 9., 9.]])

In [126]:
arr4d[[3,5,7]]

array([[4., 4., 4., 4., 4., 4., 4., 4., 4., 4.],
       [6., 6., 6., 6., 6., 6., 6., 6., 6., 6.],
       [8., 8., 8., 8., 8., 8., 8., 8., 8., 8.]])

In [127]:
arr2 = np.arange(1,11)

In [128]:
arr2

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [129]:
arr2 > 3

array([False, False, False,  True,  True,  True,  True,  True,  True,
        True])

In [130]:
bool_arr = arr2 > 4

In [131]:
bool_arr

array([False, False, False, False,  True,  True,  True,  True,  True,
        True])

In [132]:
arr2[bool_arr]

array([ 5,  6,  7,  8,  9, 10])

In [133]:
arr2[arr>5]

array([ 7,  8,  9, 10])

In [134]:
x = 2
arr2[arr2>x]

array([ 3,  4,  5,  6,  7,  8,  9, 10])