In [1]:
import numpy as np

In [2]:
arr = np.arange(0,11)

In [3]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [5]:
# +

arr + arr

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18, 20])

In [7]:
# -
arr - arr

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [8]:
arr + 25

array([25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35])

In [9]:
arr *2

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18, 20])

In [11]:
arr/arr

C:\Users\Lenovo\Anaconda3\lib\site-packages\ipykernel_launcher.py:1: RuntimeWarning: invalid value encountered in true_divide
  """Entry point for launching an IPython kernel.


array([nan,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.])

In [12]:
1/arr

C:\Users\Lenovo\Anaconda3\lib\site-packages\ipykernel_launcher.py:1: RuntimeWarning: divide by zero encountered in true_divide
  """Entry point for launching an IPython kernel.


array([       inf, 1.        , 0.5       , 0.33333333, 0.25      ,
       0.2       , 0.16666667, 0.14285714, 0.125     , 0.11111111,
       0.1       ])

In [17]:
arr2= np.random.randint(25,100,25)

In [18]:
arr2

array([25, 59, 45, 42, 84, 46, 66, 68, 34, 54, 26, 59, 44, 25, 42, 54, 26,
       36, 81, 92, 62, 26, 26, 98, 94])

In [19]:
np.sqrt(arr2)

array([5.        , 7.68114575, 6.70820393, 6.4807407 , 9.16515139,
       6.78232998, 8.1240384 , 8.24621125, 5.83095189, 7.34846923,
       5.09901951, 7.68114575, 6.63324958, 5.        , 6.4807407 ,
       7.34846923, 5.09901951, 6.        , 9.        , 9.59166305,
       7.87400787, 5.09901951, 5.09901951, 9.89949494, 9.69535971])

In [20]:
np.exp(arr2)

array([7.20048993e+10, 4.20121040e+25, 3.49342711e+19, 1.73927494e+18,
       3.02507732e+36, 9.49611942e+19, 4.60718663e+28, 3.40427605e+29,
       5.83461743e+14, 2.83075330e+23, 1.95729609e+11, 4.20121040e+25,
       1.28516001e+19, 7.20048993e+10, 1.73927494e+18, 2.83075330e+23,
       1.95729609e+11, 4.31123155e+15, 1.50609731e+35, 9.01762841e+39,
       8.43835667e+26, 1.95729609e+11, 1.95729609e+11, 3.63797095e+42,
       6.66317622e+40])

In [21]:
np.max(arr2)

98

In [22]:
np.sin(arr)

array([ 0.        ,  0.84147098,  0.90929743,  0.14112001, -0.7568025 ,
       -0.95892427, -0.2794155 ,  0.6569866 ,  0.98935825,  0.41211849,
       -0.54402111])

In [23]:
np.log(arr2)

array([3.21887582, 4.07753744, 3.80666249, 3.73766962, 4.4308168 ,
       3.8286414 , 4.18965474, 4.21950771, 3.52636052, 3.98898405,
       3.25809654, 4.07753744, 3.78418963, 3.21887582, 3.73766962,
       3.98898405, 3.25809654, 3.58351894, 4.39444915, 4.52178858,
       4.12713439, 3.25809654, 3.25809654, 4.58496748, 4.54329478])

In [24]:
import numpy as np

In [28]:
a0=np.zeros(10)

In [29]:
a0

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [30]:
a1=np.ones(10)

In [31]:
a1

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [38]:
a5 = np.ones(10) * 5

In [39]:
a5

array([5., 5., 5., 5., 5., 5., 5., 5., 5., 5.])

In [42]:
a6 = np.arange(10,51)

In [43]:
a6

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43,
       44, 45, 46, 47, 48, 49, 50])

In [44]:
a7 =np.arange(10,51,2)

In [45]:
a7

array([10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30, 32, 34, 36, 38, 40, 42,
       44, 46, 48, 50])

In [48]:
a8 = np.arange(9).reshape(3,3)

In [49]:
a8

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [50]:
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [51]:
np.random.rand(1)

array([0.32772402])

In [52]:
np.random.randn(25)

array([ 1.5366636 ,  0.36125136, -2.15584949, -0.08300225,  2.41017262,
       -0.97966161,  0.65514954,  1.54482699,  0.46421777, -1.33354961,
        0.72104319, -0.49595059, -0.56634139, -0.46575542, -0.43850248,
        0.91630338, -0.29186169, -0.05010035,  0.47676067, -1.40463614,
       -0.35485585, -0.56559659,  0.51770407,  1.17407318,  0.51090261])

In [53]:
np.arange(1,101).reshape(10,10) / 10

array([[ 0.1,  0.2,  0.3,  0.4,  0.5,  0.6,  0.7,  0.8,  0.9,  1. ],
       [ 1.1,  1.2,  1.3,  1.4,  1.5,  1.6,  1.7,  1.8,  1.9,  2. ],
       [ 2.1,  2.2,  2.3,  2.4,  2.5,  2.6,  2.7,  2.8,  2.9,  3. ],
       [ 3.1,  3.2,  3.3,  3.4,  3.5,  3.6,  3.7,  3.8,  3.9,  4. ],
       [ 4.1,  4.2,  4.3,  4.4,  4.5,  4.6,  4.7,  4.8,  4.9,  5. ],
       [ 5.1,  5.2,  5.3,  5.4,  5.5,  5.6,  5.7,  5.8,  5.9,  6. ],
       [ 6.1,  6.2,  6.3,  6.4,  6.5,  6.6,  6.7,  6.8,  6.9,  7. ],
       [ 7.1,  7.2,  7.3,  7.4,  7.5,  7.6,  7.7,  7.8,  7.9,  8. ],
       [ 8.1,  8.2,  8.3,  8.4,  8.5,  8.6,  8.7,  8.8,  8.9,  9. ],
       [ 9.1,  9.2,  9.3,  9.4,  9.5,  9.6,  9.7,  9.8,  9.9, 10. ]])

In [55]:
np.linspace(0,1,20)

array([0.        , 0.05263158, 0.10526316, 0.15789474, 0.21052632,
       0.26315789, 0.31578947, 0.36842105, 0.42105263, 0.47368421,
       0.52631579, 0.57894737, 0.63157895, 0.68421053, 0.73684211,
       0.78947368, 0.84210526, 0.89473684, 0.94736842, 1.        ])

In [56]:
mat = np.arange(1,26).reshape(5,5)
mat

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25]])

In [60]:
mat[2:5,1:5]

array([[12, 13, 14, 15],
       [17, 18, 19, 20],
       [22, 23, 24, 25]])

In [69]:
mat[3:4,4:]

array([[20]])

In [76]:
mat[0:3,1:2]

array([[ 2],
       [ 7],
       [12]])

In [78]:
mat[4:]

array([[21, 22, 23, 24, 25]])

In [80]:
mat[3:5]

array([[16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25]])

In [81]:
mat.sum()

325

In [82]:
mat.std()

7.211102550927978

In [84]:
mat.sum(axis=0)

array([55, 60, 65, 70, 75])

In [88]:
mat.sum(axis=0)

array([55, 60, 65, 70, 75])