# Variable assignment

In [2]:
name_var = 2


In [3]:
x = 2
y = 3

In [4]:
z = (3+x)*(4%3)

In [5]:
z

5

# String

In [7]:
'Single quotes'

'Single quotes'

In [8]:
"double quotes"

'double quotes'

# Printing

In [10]:
x = 'Hello'

In [11]:
x

'Hello'

In [12]:
print(x)

Hello


In [13]:
age = 25
name = 'Andri'

In [14]:
print('Nama saya {a}, dan saya berumur {b} tahun'.format(a=name,b=age))

Nama saya Andri, dan saya berumur 25 tahun


In [16]:
print('Nama saya {}, dan saya berumur {} tahun'.format(name,age))

Nama saya Andri, dan saya berumur 25 tahun


In [17]:
nama = 'Andri Eko Saputro'

In [18]:
nama[0]

'A'

In [19]:
nama[0:]

'Andri Eko Saputro'

In [20]:
nama[:2]

'An'

In [22]:
nama[5:9]

' Eko'

# List


In [23]:
['F','I','G','H','T','I','N','G']

['F', 'I', 'G', 'H', 'T', 'I', 'N', 'G']

In [24]:
list = ['F','I','G','H','T','I','N','G']

In [25]:
list.append('!')

In [26]:
list

['F', 'I', 'G', 'H', 'T', 'I', 'N', 'G', '!']

In [27]:
list[0]

'F'

In [28]:
list[:6]

['F', 'I', 'G', 'H', 'T', 'I']

In [29]:
list[2:9]

['G', 'H', 'T', 'I', 'N', 'G', '!']

# Nest

In [31]:
nest = ['a','b','c',[4,5,['Good!']]]

In [32]:
nest[2]

'c'

In [36]:
nest[3][2][0]

'Good!'

In [37]:
print(nest[3][2][0])

Good!


# Dictionaries

In [38]:
dict = {'a':'apple','b':'banana','c':'citrus'}

In [39]:
dict

{'a': 'apple', 'b': 'banana', 'c': 'citrus'}

In [41]:
dict['a']

'apple'

# Tuples

In [43]:
tup = (1,2,3,4,5)

In [44]:
tup[0]

1

In [45]:
tup

(1, 2, 3, 4, 5)

In [46]:
tup[2] = 22

TypeError: 'tuple' object does not support item assignment

# Sets

In [48]:
sets = {1,2,3,4,5}

In [49]:
sets

{1, 2, 3, 4, 5}

In [51]:
sets.add(6)

In [52]:
sets

{1, 2, 3, 4, 5, 6}

# Comparison Operators

In [54]:
True and True

True

In [55]:
True and False

False

In [56]:
False and True

False

In [57]:
True or True

True

In [58]:
False or True

True

In [59]:
False or False

False

In [60]:
2 == '2'

False

In [64]:
2 == 2

True

# If,elif,else Statements

In [67]:
if 1 > 2:
    print('yup!')
    
#Nothing heppen!

In [68]:
if 2 < 3:
    print('Good!')

Good!


In [70]:
if True:
    x = 2 * 2

In [71]:
x

4

In [72]:
if 1==2:
    print('benar')
else:
    print('salah')

salah


In [75]:
if 'a' == 'b':
    print('Salah')
elif 'b' == 'c':
    print('bukan')
elif 'd' == 'd':
    print('Yup')
else:
    print('Gak tau')

Yup


# For Loops

In [77]:
deret = [1,45,35,67,97,33,57,32,13,43]

In [79]:
for x in deret:
    print (x-1)

0
44
34
66
96
32
56
31
12
42


In [99]:
for x in deret:
    if x%2==0:
        print('genap')
    else:
        print('ganjil')
        
        

ganjil
ganjil
ganjil
ganjil
ganjil
ganjil
ganjil
genap
ganjil
ganjil


In [105]:
range(1,100)

range(1, 100)

In [115]:
seq = range(1,10)

In [116]:
seq

range(1, 10)

In [117]:
for x in seq:
    print(x)


1
2
3
4
5
6
7
8
9


In [123]:
num = int(input('Masukan bilangan='))

if num > 1:
    for i in range(2,num):
        if(num % i) == 0:
            print('Bukan bilangan prima')
            print(i,'kali',num//i,'=',num)
            break
    else:
        print('Bilangan prima')
else:
    print(num, 'Bukan bilangan prima')

Masukan bilangan=9
Bukan bilangan prima
3 kali 3 = 9


In [130]:
lower =100
upper =200

print('Bilangan prima andata',lower,'dan',upper,'=')

for num in range(lower,upper+1):
    if num > 1:
        for i in range(2,num):
            if(num % 1) == 0:
                break 
        else:
            print(num)

Bilangan prima andata 100 dan 200 =


# WHile loops

In [2]:
i = 1

while i < 5:
    print('Angka ke: {}'.format(i))
    i = i+1

Angka ke: 1
Angka ke: 2
Angka ke: 3
Angka ke: 4


In [3]:
range(1,11)

range(1, 11)

In [6]:
for i in range(1,11):
    print(i)

1
2
3
4
5
6
7
8
9
10


In [7]:
x = [1,2,3,4,5]

In [9]:
out=[]
for i in x:
    out.append(i**2)
print(out)

[1, 4, 9, 16, 25]


In [10]:
[num**2 for num in x]

[1, 4, 9, 16, 25]

In [11]:
out=[num**2 for num in x]

In [12]:
out

[1, 4, 9, 16, 25]

In [15]:
def times(var):
    return var*2

In [16]:
times(2)

4

In [17]:
data = [12,34,57,45,75,86]

In [18]:
map(times,data)

In [19]:
list(map(times,data))

[24, 68, 114, 90, 150, 172]

# Lambda

In [21]:
def chart(var):return var**2

In [22]:
lambda var:var**2

<function __main__.<lambda>(var)>

In [26]:
n = lambda var:var**2

In [27]:
n

<function __main__.<lambda>(var)>

In [28]:
list(map(lambda num:num//2,data))

[6, 17, 28, 22, 37, 43]

In [29]:
filter(lambda num:num//2,data)

In [33]:
list(filter(lambda num:num%2==1,data))

[57, 45, 75]

# Numpy

In [34]:
import numpy as np

In [35]:
lst = [34,56,67,89,90]

In [36]:
np.array(lst)

array([34, 56, 67, 89, 90])

In [37]:
mtx =[[23,46,45],[56,12,45],[45,67,53]]

In [38]:
np.array(mtx)

array([[23, 46, 45],
       [56, 12, 45],
       [45, 67, 53]])

# arange

In [39]:
np.arange(0,11)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [40]:
np.arange(0,11,2)

array([ 0,  2,  4,  6,  8, 10])

In [41]:
np.zeros((4,4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [42]:
np.ones((4,4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [44]:
np.linspace(0,25,5)

array([ 0.  ,  6.25, 12.5 , 18.75, 25.  ])

In [46]:
np.linspace(0,100,25)

array([  0.        ,   4.16666667,   8.33333333,  12.5       ,
        16.66666667,  20.83333333,  25.        ,  29.16666667,
        33.33333333,  37.5       ,  41.66666667,  45.83333333,
        50.        ,  54.16666667,  58.33333333,  62.5       ,
        66.66666667,  70.83333333,  75.        ,  79.16666667,
        83.33333333,  87.5       ,  91.66666667,  95.83333333,
       100.        ])

In [47]:
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [48]:
np.random.rand(2)

array([0.94512305, 0.29397003])

In [49]:
np.random.rand(3,3)

array([[0.64040112, 0.43792907, 0.15038089],
       [0.47052865, 0.30572155, 0.98898971],
       [0.51715198, 0.30079396, 0.40383302]])

In [50]:
np.random.randint(1,100)

18

In [75]:
np.random.randint(10,100,25)

array([76, 84, 80, 28, 66, 94, 43, 96, 48, 27, 31, 96, 64, 86, 86, 73, 40,
       66, 79, 32, 64, 85, 60, 62, 35])

In [89]:
arr = np.arange(2,100,10)

In [90]:
arr

array([ 2, 12, 22, 32, 42, 52, 62, 72, 82, 92])

In [78]:
rarr = np.random.randint(50,100,20)

In [79]:
rarr

array([97, 58, 72, 75, 55, 88, 99, 82, 51, 94, 61, 55, 93, 54, 57, 59, 96,
       68, 70, 99])

In [94]:
arr.reshape(2,5)

array([[ 2, 12, 22, 32, 42],
       [52, 62, 72, 82, 92]])

In [95]:
a1 = np.arange(4,100,10)

In [96]:
a1

array([ 4, 14, 24, 34, 44, 54, 64, 74, 84, 94])

In [101]:
a2 = np.random.randint(90,100,10)

In [102]:
a2

array([95, 99, 96, 96, 91, 93, 94, 95, 91, 97])

In [103]:
a1.max()

94

In [104]:
a2.max()

99

In [105]:
a1.min()

4

In [106]:
a2.min()

91

In [107]:
a1.argmax()

9

In [108]:
a2.argmax()

1

In [109]:
a1.argmin()

0

In [110]:
a2.argmin()

4

In [111]:
a1.shape

(10,)

In [112]:
a2.shape

(10,)

In [113]:
a1.reshape(2,5)

array([[ 4, 14, 24, 34, 44],
       [54, 64, 74, 84, 94]])

In [114]:
a2.reshape(5,2)

array([[95, 99],
       [96, 96],
       [91, 93],
       [94, 95],
       [91, 97]])

In [115]:
a1.reshape(5,2).shape

(5, 2)

In [116]:
a1

array([ 4, 14, 24, 34, 44, 54, 64, 74, 84, 94])

In [117]:
a1.dtype

dtype('int32')

In [118]:
a2.dtype

dtype('int32')

# Numpy

In [136]:
a3 = np.arange(1,16)

In [137]:
a3

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15])

In [138]:
a3[3]

4

In [139]:
a3[:7]

array([1, 2, 3, 4, 5, 6, 7])

In [140]:
#broadcasting

In [141]:
a3[:3] = 25

In [142]:
a3

array([25, 25, 25,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15])

In [143]:
slice_arr = a3[2:7]

In [144]:
slice_arr

array([25,  4,  5,  6,  7])

In [145]:
a3_copy = a3.copy()

In [146]:
a3_copy

array([25, 25, 25,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15])

In [147]:
a3_copy[0:6]=50

In [148]:
a3_copy

array([50, 50, 50, 50, 50, 50,  7,  8,  9, 10, 11, 12, 13, 14, 15])

In [149]:
a3

array([25, 25, 25,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15])

# Indexing a 2d array (matrix)

In [151]:
arr2d = np.array(([1,2,3],[2,4,6],[3,6,9],[4,8,12]))

In [152]:
arr2d

array([[ 1,  2,  3],
       [ 2,  4,  6],
       [ 3,  6,  9],
       [ 4,  8, 12]])

In [159]:
arr2d.reshape(3,4)

array([[ 1,  2,  3,  2],
       [ 4,  6,  3,  6],
       [ 9,  4,  8, 12]])

In [161]:
arr2d[1]

array([2, 4, 6])

In [164]:
arr2d[3,1]

8

In [169]:
arr2d[:1,:2]

array([[1, 2]])

In [170]:
a4 = np.arange(0,25)

In [171]:
a4

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24])

In [176]:
a4 > 10

array([False, False, False, False, False, False, False, False, False,
       False, False,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True])

In [177]:
bool_arr = a4 > 15

In [178]:
bool_arr

array([False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False,  True,  True,
        True,  True,  True,  True,  True,  True,  True])

In [179]:
a4[a4>18]

array([19, 20, 21, 22, 23, 24])