In [1]:
import numpy as np

In [2]:
lists = [32,64,57,53,11,64]

In [3]:
lists

[32, 64, 57, 53, 11, 64]

In [4]:
np.array(lists)

array([32, 64, 57, 53, 11, 64])

In [5]:
mtx =[[1,2,3],[9,10,11],[34,53,64]]

In [8]:
mtx

[[1, 2, 3], [9, 10, 11], [34, 53, 64]]

In [9]:
np.array(mtx)

array([[ 1,  2,  3],
       [ 9, 10, 11],
       [34, 53, 64]])

In [10]:
np.arange(0,11)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [11]:
np.arange(0,100,10)

array([ 0, 10, 20, 30, 40, 50, 60, 70, 80, 90])

In [12]:
np.zeros(3)

array([0., 0., 0.])

In [13]:
np.ones(4)

array([1., 1., 1., 1.])

In [16]:
np.zeros((4,4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [17]:
np.ones((3,3))

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [19]:
np.linspace(0,10,5)

array([ 0. ,  2.5,  5. ,  7.5, 10. ])

In [20]:
np.linspace(4,10,5)

array([ 4. ,  5.5,  7. ,  8.5, 10. ])

In [21]:
np.eye(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [22]:
np.random.rand(1)

array([0.68169618])

In [23]:
np.random.rand(2)

array([0.52047165, 0.95317829])

In [24]:
np.random.rand(3,3)

array([[0.38299112, 0.63036088, 0.73601893],
       [0.78671159, 0.6000169 , 0.31341706],
       [0.46049107, 0.87057735, 0.740885  ]])

In [25]:
np.random.randint(1,20)

4

In [26]:
np.random.randint(1,1000)

687

In [28]:
np.random.randint(1,25,12)

array([18, 16, 17, 14,  9,  8, 12, 21, 13,  6, 23, 18])

In [29]:
np.random.randint(1,10,10)

array([3, 4, 6, 5, 1, 2, 6, 2, 4, 8])

In [30]:
arr = np.arange(26)

In [31]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25])

In [32]:
ranarr = np.random.randint(0,101,10)

In [33]:
ranarr

array([56, 88, 64, 18,  2, 73, 58, 50, 21, 79])

In [34]:
arr.reshape(13,2)

array([[ 0,  1],
       [ 2,  3],
       [ 4,  5],
       [ 6,  7],
       [ 8,  9],
       [10, 11],
       [12, 13],
       [14, 15],
       [16, 17],
       [18, 19],
       [20, 21],
       [22, 23],
       [24, 25]])

In [35]:
arr.reshape(2,13)

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12],
       [13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25]])

In [36]:
ar1 = np.random.randint(0,101,25)

In [37]:
ar1

array([ 6, 56, 72, 33, 94, 98, 20, 23, 30, 11, 94, 79, 21, 52, 90, 32, 34,
        4, 81, 82, 51, 48, 61, 34, 99])

In [38]:
ar1.reshape(5,5)

array([[ 6, 56, 72, 33, 94],
       [98, 20, 23, 30, 11],
       [94, 79, 21, 52, 90],
       [32, 34,  4, 81, 82],
       [51, 48, 61, 34, 99]])

In [39]:
ar2 = np.random.randint(0,101,72)

In [40]:
ar2

array([56, 27, 43, 44, 37, 10, 66, 99, 95, 83, 97, 43, 97, 41, 92, 48, 33,
        0, 16,  0, 84, 69, 93, 94, 44, 85, 61, 87, 93, 68, 45,  3, 30, 87,
        8, 32, 60, 73, 48, 23, 98, 58, 14, 48, 17, 38, 84, 79, 62, 55, 27,
       97, 25, 54, 82, 36, 29, 90, 89, 51, 19, 69, 18,  2,  5, 65, 29, 20,
       80, 44, 89, 20])

In [41]:
ar2.reshape(9,8)

array([[56, 27, 43, 44, 37, 10, 66, 99],
       [95, 83, 97, 43, 97, 41, 92, 48],
       [33,  0, 16,  0, 84, 69, 93, 94],
       [44, 85, 61, 87, 93, 68, 45,  3],
       [30, 87,  8, 32, 60, 73, 48, 23],
       [98, 58, 14, 48, 17, 38, 84, 79],
       [62, 55, 27, 97, 25, 54, 82, 36],
       [29, 90, 89, 51, 19, 69, 18,  2],
       [ 5, 65, 29, 20, 80, 44, 89, 20]])

In [42]:
ar2.reshape(12,6)

array([[56, 27, 43, 44, 37, 10],
       [66, 99, 95, 83, 97, 43],
       [97, 41, 92, 48, 33,  0],
       [16,  0, 84, 69, 93, 94],
       [44, 85, 61, 87, 93, 68],
       [45,  3, 30, 87,  8, 32],
       [60, 73, 48, 23, 98, 58],
       [14, 48, 17, 38, 84, 79],
       [62, 55, 27, 97, 25, 54],
       [82, 36, 29, 90, 89, 51],
       [19, 69, 18,  2,  5, 65],
       [29, 20, 80, 44, 89, 20]])

In [43]:
ar2

array([56, 27, 43, 44, 37, 10, 66, 99, 95, 83, 97, 43, 97, 41, 92, 48, 33,
        0, 16,  0, 84, 69, 93, 94, 44, 85, 61, 87, 93, 68, 45,  3, 30, 87,
        8, 32, 60, 73, 48, 23, 98, 58, 14, 48, 17, 38, 84, 79, 62, 55, 27,
       97, 25, 54, 82, 36, 29, 90, 89, 51, 19, 69, 18,  2,  5, 65, 29, 20,
       80, 44, 89, 20])

In [44]:
ar2.max()

99

In [45]:
ar2.min()

0

In [46]:
ar2.argmax()

7

In [47]:
ar2.argmin()

17

In [48]:
ar2.shape

(72,)

In [50]:
ar2.reshape(8,9)

array([[56, 27, 43, 44, 37, 10, 66, 99, 95],
       [83, 97, 43, 97, 41, 92, 48, 33,  0],
       [16,  0, 84, 69, 93, 94, 44, 85, 61],
       [87, 93, 68, 45,  3, 30, 87,  8, 32],
       [60, 73, 48, 23, 98, 58, 14, 48, 17],
       [38, 84, 79, 62, 55, 27, 97, 25, 54],
       [82, 36, 29, 90, 89, 51, 19, 69, 18],
       [ 2,  5, 65, 29, 20, 80, 44, 89, 20]])

In [52]:
arr.dtype

dtype('int32')

In [53]:
ar2.dtype

dtype('int32')

In [54]:
ar2

array([56, 27, 43, 44, 37, 10, 66, 99, 95, 83, 97, 43, 97, 41, 92, 48, 33,
        0, 16,  0, 84, 69, 93, 94, 44, 85, 61, 87, 93, 68, 45,  3, 30, 87,
        8, 32, 60, 73, 48, 23, 98, 58, 14, 48, 17, 38, 84, 79, 62, 55, 27,
       97, 25, 54, 82, 36, 29, 90, 89, 51, 19, 69, 18,  2,  5, 65, 29, 20,
       80, 44, 89, 20])

In [55]:
ar2[9]

83

In [56]:
ar2[0:4]

array([56, 27, 43, 44])

In [57]:
ar2[:10] = 0

In [58]:
ar2

array([ 0,  0,  0,  0,  0,  0,  0,  0,  0,  0, 97, 43, 97, 41, 92, 48, 33,
        0, 16,  0, 84, 69, 93, 94, 44, 85, 61, 87, 93, 68, 45,  3, 30, 87,
        8, 32, 60, 73, 48, 23, 98, 58, 14, 48, 17, 38, 84, 79, 62, 55, 27,
       97, 25, 54, 82, 36, 29, 90, 89, 51, 19, 69, 18,  2,  5, 65, 29, 20,
       80, 44, 89, 20])

In [59]:
ar2_copy = ar2.copy()

In [61]:
ar2_copy

array([ 0,  0,  0,  0,  0,  0,  0,  0,  0,  0, 97, 43, 97, 41, 92, 48, 33,
        0, 16,  0, 84, 69, 93, 94, 44, 85, 61, 87, 93, 68, 45,  3, 30, 87,
        8, 32, 60, 73, 48, 23, 98, 58, 14, 48, 17, 38, 84, 79, 62, 55, 27,
       97, 25, 54, 82, 36, 29, 90, 89, 51, 19, 69, 18,  2,  5, 65, 29, 20,
       80, 44, 89, 20])

In [62]:
ar2_copy[0:10] = 100

In [63]:
ar2_copy

array([100, 100, 100, 100, 100, 100, 100, 100, 100, 100,  97,  43,  97,
        41,  92,  48,  33,   0,  16,   0,  84,  69,  93,  94,  44,  85,
        61,  87,  93,  68,  45,   3,  30,  87,   8,  32,  60,  73,  48,
        23,  98,  58,  14,  48,  17,  38,  84,  79,  62,  55,  27,  97,
        25,  54,  82,  36,  29,  90,  89,  51,  19,  69,  18,   2,   5,
        65,  29,  20,  80,  44,  89,  20])

In [64]:
ar2

array([ 0,  0,  0,  0,  0,  0,  0,  0,  0,  0, 97, 43, 97, 41, 92, 48, 33,
        0, 16,  0, 84, 69, 93, 94, 44, 85, 61, 87, 93, 68, 45,  3, 30, 87,
        8, 32, 60, 73, 48, 23, 98, 58, 14, 48, 17, 38, 84, 79, 62, 55, 27,
       97, 25, 54, 82, 36, 29, 90, 89, 51, 19, 69, 18,  2,  5, 65, 29, 20,
       80, 44, 89, 20])

In [65]:
arr_copy = arr.copy()

In [66]:
arr_copy

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25])

In [67]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25])

In [68]:
arr.shape

(26,)

In [70]:
arr_copy[:]= 0

In [71]:
arr_copy

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0])

In [72]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25])

In [79]:
arr_2d = np.array(([1,2,3],[8,19,0],[7,24,3],[3,12,23]))

In [80]:
arr_2d

array([[ 1,  2,  3],
       [ 8, 19,  0],
       [ 7, 24,  3],
       [ 3, 12, 23]])

In [81]:
arr_2d.shape

(4, 3)

In [82]:
arr_2d.reshape(6,2)

array([[ 1,  2],
       [ 3,  8],
       [19,  0],
       [ 7, 24],
       [ 3,  3],
       [12, 23]])

In [83]:
arr_2d

array([[ 1,  2,  3],
       [ 8, 19,  0],
       [ 7, 24,  3],
       [ 3, 12, 23]])

In [89]:
arr_2d[1:2,1:2]

array([[19]])

In [99]:
arr_2d[2:4,1:3]

array([[24,  3],
       [12, 23]])

In [100]:
bool_arr = np.arange(0,26)

In [101]:
bool_arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25])

In [102]:
fungsi = bool_arr > 12

In [103]:
fungsi

array([False, False, False, False, False, False, False, False, False,
       False, False, False, False,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True])

In [104]:
bool_arr[fungsi]

array([13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25])

In [105]:
bool_ar2 = np.random.randint(0,101,30)

In [106]:
bool_ar2

array([75, 29, 67, 12, 97, 16, 70, 91, 11, 22, 16, 53, 49, 44, 22, 81, 21,
        5,  7, 93, 56, 25, 81, 59, 59, 58, 68, 87, 90, 13])

In [107]:
func = bool_ar2 > 50

In [108]:
func

array([ True, False,  True, False,  True, False,  True,  True, False,
       False, False,  True, False, False, False,  True, False, False,
       False,  True,  True, False,  True,  True,  True,  True,  True,
        True,  True, False])

In [110]:
bool_ar2[func]

array([75, 67, 97, 70, 91, 53, 81, 93, 56, 81, 59, 59, 58, 68, 87, 90])

In [111]:
bool_arr[bool_arr>20]

array([21, 22, 23, 24, 25])

In [112]:
bool_ar2[bool_ar2>60]

array([75, 67, 97, 70, 91, 81, 93, 81, 68, 87, 90])

In [113]:
ar4 = np.random.randint(0,100,25).reshape(5,5)

In [114]:
ar4

array([[37, 64,  3, 15, 89],
       [94, 79, 74, 37, 78],
       [21, 12, 33,  1, 73],
       [18, 75, 10, 74, 51],
       [ 6, 17, 49, 86, 39]])

In [115]:
ar4[ar4>50]

array([64, 89, 94, 79, 74, 78, 73, 75, 74, 51, 86])

In [116]:
bool_func = ar4>70

In [117]:
bool_func

array([[False, False, False, False,  True],
       [ True,  True,  True, False,  True],
       [False, False, False, False,  True],
       [False,  True, False,  True, False],
       [False, False, False,  True, False]])

In [118]:
ar4[bool_func]

array([89, 94, 79, 74, 78, 73, 75, 74, 86])

In [119]:
ar4[ar4>70]

array([89, 94, 79, 74, 78, 73, 75, 74, 86])

In [120]:
import numpy as np

In [124]:
ar5 = np.random.randint(1,50,50).reshape(5,10)

In [125]:
ar5

array([[21, 45, 48, 18, 11, 49, 31,  6, 34, 19],
       [25, 38, 39, 47,  5, 25, 25, 34, 30, 41],
       [47, 12,  6, 29, 36, 44, 33, 27, 10, 17],
       [19, 40, 43, 33, 14, 43, 42, 46, 34,  6],
       [18, 28,  1, 27, 33, 27, 28,  4, 29, 42]])

In [126]:
ar5 -2

array([[19, 43, 46, 16,  9, 47, 29,  4, 32, 17],
       [23, 36, 37, 45,  3, 23, 23, 32, 28, 39],
       [45, 10,  4, 27, 34, 42, 31, 25,  8, 15],
       [17, 38, 41, 31, 12, 41, 40, 44, 32,  4],
       [16, 26, -1, 25, 31, 25, 26,  2, 27, 40]])

In [127]:
ar5 - ar5

array([[0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0]])

In [128]:
ar5

array([[21, 45, 48, 18, 11, 49, 31,  6, 34, 19],
       [25, 38, 39, 47,  5, 25, 25, 34, 30, 41],
       [47, 12,  6, 29, 36, 44, 33, 27, 10, 17],
       [19, 40, 43, 33, 14, 43, 42, 46, 34,  6],
       [18, 28,  1, 27, 33, 27, 28,  4, 29, 42]])

In [129]:
ar5 * 2

array([[42, 90, 96, 36, 22, 98, 62, 12, 68, 38],
       [50, 76, 78, 94, 10, 50, 50, 68, 60, 82],
       [94, 24, 12, 58, 72, 88, 66, 54, 20, 34],
       [38, 80, 86, 66, 28, 86, 84, 92, 68, 12],
       [36, 56,  2, 54, 66, 54, 56,  8, 58, 84]])

In [130]:
np.sqrt(ar5)

array([[4.58257569, 6.70820393, 6.92820323, 4.24264069, 3.31662479,
        7.        , 5.56776436, 2.44948974, 5.83095189, 4.35889894],
       [5.        , 6.164414  , 6.244998  , 6.8556546 , 2.23606798,
        5.        , 5.        , 5.83095189, 5.47722558, 6.40312424],
       [6.8556546 , 3.46410162, 2.44948974, 5.38516481, 6.        ,
        6.63324958, 5.74456265, 5.19615242, 3.16227766, 4.12310563],
       [4.35889894, 6.32455532, 6.55743852, 5.74456265, 3.74165739,
        6.55743852, 6.4807407 , 6.78232998, 5.83095189, 2.44948974],
       [4.24264069, 5.29150262, 1.        , 5.19615242, 5.74456265,
        5.19615242, 5.29150262, 2.        , 5.38516481, 6.4807407 ]])

In [131]:
bool_ar5 = ar5 > 25

In [132]:
bool_ar5

array([[False,  True,  True, False, False,  True,  True, False,  True,
        False],
       [False,  True,  True,  True, False, False, False,  True,  True,
         True],
       [ True, False, False,  True,  True,  True,  True,  True, False,
        False],
       [False,  True,  True,  True, False,  True,  True,  True,  True,
        False],
       [False,  True, False,  True,  True,  True,  True, False,  True,
         True]])

In [133]:
ar5[bool_ar5]

array([45, 48, 49, 31, 34, 38, 39, 47, 34, 30, 41, 47, 29, 36, 44, 33, 27,
       40, 43, 33, 43, 42, 46, 34, 28, 27, 33, 27, 28, 29, 42])

In [134]:
ar5[ar5>25]

array([45, 48, 49, 31, 34, 38, 39, 47, 34, 30, 41, 47, 29, 36, 44, 33, 27,
       40, 43, 33, 43, 42, 46, 34, 28, 27, 33, 27, 28, 29, 42])

In [135]:
np.exp(ar5)

array([[1.31881573e+09, 3.49342711e+19, 7.01673591e+20, 6.56599691e+07,
        5.98741417e+04, 1.90734657e+21, 2.90488497e+13, 4.03428793e+02,
        5.83461743e+14, 1.78482301e+08],
       [7.20048993e+10, 3.18559318e+16, 8.65934004e+16, 2.58131289e+20,
        1.48413159e+02, 7.20048993e+10, 7.20048993e+10, 5.83461743e+14,
        1.06864746e+13, 6.39843494e+17],
       [2.58131289e+20, 1.62754791e+05, 4.03428793e+02, 3.93133430e+12,
        4.31123155e+15, 1.28516001e+19, 2.14643580e+14, 5.32048241e+11,
        2.20264658e+04, 2.41549528e+07],
       [1.78482301e+08, 2.35385267e+17, 4.72783947e+18, 2.14643580e+14,
        1.20260428e+06, 4.72783947e+18, 1.73927494e+18, 9.49611942e+19,
        5.83461743e+14, 4.03428793e+02],
       [6.56599691e+07, 1.44625706e+12, 2.71828183e+00, 5.32048241e+11,
        2.14643580e+14, 5.32048241e+11, 1.44625706e+12, 5.45981500e+01,
        3.93133430e+12, 1.73927494e+18]])

In [136]:
np.max(ar5)

49

In [137]:
np.min(ar5)

1

In [138]:
np.argmax(ar5)

5

In [139]:
np.argmin(ar5)

42

In [142]:
arr_log = np.arange(0,101,10)

In [143]:
arr_log

array([  0,  10,  20,  30,  40,  50,  60,  70,  80,  90, 100])

In [144]:
np.log(arr_log)

C:\Users\Lenovo\Anaconda3\lib\site-packages\ipykernel_launcher.py:1: RuntimeWarning: divide by zero encountered in log
  """Entry point for launching an IPython kernel.


array([      -inf, 2.30258509, 2.99573227, 3.40119738, 3.68887945,
       3.91202301, 4.09434456, 4.24849524, 4.38202663, 4.49980967,
       4.60517019])

In [145]:
np.linspace(0,10,20)

array([ 0.        ,  0.52631579,  1.05263158,  1.57894737,  2.10526316,
        2.63157895,  3.15789474,  3.68421053,  4.21052632,  4.73684211,
        5.26315789,  5.78947368,  6.31578947,  6.84210526,  7.36842105,
        7.89473684,  8.42105263,  8.94736842,  9.47368421, 10.        ])

In [146]:
ar5.sum()

1409

In [147]:
ar5.std()

13.402522150699845

In [148]:
ar5.sum(axis=0)

array([130, 163, 137, 154,  99, 188, 159, 117, 137, 125])

In [149]:
import numpy as np

In [150]:
import pandas as pd

In [151]:
labels = ['a','b','c','d']

In [152]:
list1 = [1,2,3,4]

In [153]:
ar6 = np.array([10,20,30,40])

In [154]:
dicts = {'a': 11,'b':12,'c':33,'d':45}

In [156]:
pd.Series(data=list1)

0    1
1    2
2    3
3    4
dtype: int64

In [157]:
pd.Series(data=dicts)

a    11
b    12
c    33
d    45
dtype: int64

In [158]:
pd.Series(data=labels)

0    a
1    b
2    c
3    d
dtype: object

In [159]:
pd.Series(data=ar6)

0    10
1    20
2    30
3    40
dtype: int32

In [161]:
pd.Series(data=ar6,index=labels)

a    10
b    20
c    30
d    40
dtype: int32

In [164]:
country = pd.Series(['ID','US','GB','KR'],index=['Indonesia','USA','England','South Korea'])

In [165]:
country

Indonesia      ID
USA            US
England        GB
South Korea    KR
dtype: object

In [167]:
country['USA']

'US'

In [170]:
import numpy as np
import pandas as pd

from numpy.random import randn
from numpy.random import randint

In [173]:
df = pd.DataFrame(randint(0,101,36).reshape(9,4),index='A B C D E F G H I'.split(),columns='a1 b1 c1 d1'.split())

In [174]:
df

a1  b1  c1  d1
A  79  52  16  20
B  96  35  43  58
C  26  89  21  95
D  99  43  11  94
E  90  87   4  29
F  95  42  28   3
G  99  93  17  47
H  92  24  89  43
I  73  58  40  63

In [175]:
df1 = pd.DataFrame(randint(0,100,25).reshape(5,5),index='1 2 3 4 5'.split(),columns=' A B C D E'.split())

In [176]:
df1

A   B   C   D   E
1  88  84  98  75  99
2  17  43  49  92  32
3  25  96   4  78  85
4  37  61  67  79   8
5  69   8  43  14  85

In [181]:
df['a1']

A    79
B    96
C    26
D    99
E    90
F    95
G    99
H    92
I    73
Name: a1, dtype: int32

In [182]:
df1['A']

1    88
2    17
3    25
4    37
5    69
Name: A, dtype: int32

In [185]:
df[['a1','b1']]

a1  b1
A  79  52
B  96  35
C  26  89
D  99  43
E  90  87
F  95  42
G  99  93
H  92  24
I  73  58

In [189]:
df1[['A','C']]

A   C
1  88  98
2  17  49
3  25   4
4  37  67
5  69  43

In [194]:
type(df)

pandas.core.frame.DataFrame

In [195]:
df

a1  b1  c1  d1
A  79  52  16  20
B  96  35  43  58
C  26  89  21  95
D  99  43  11  94
E  90  87   4  29
F  95  42  28   3
G  99  93  17  47
H  92  24  89  43
I  73  58  40  63

In [196]:
df1

A   B   C   D   E
1  88  84  98  75  99
2  17  43  49  92  32
3  25  96   4  78  85
4  37  61  67  79   8
5  69   8  43  14  85

In [198]:
df1['F'] = df1['A'] - 10

In [199]:
df1

A   B   C   D   E   F
1  88  84  98  75  99  78
2  17  43  49  92  32   7
3  25  96   4  78  85  15
4  37  61  67  79   8  27
5  69   8  43  14  85  59

In [201]:
df1['G'] = df1['F'] // 2

In [202]:
df1

A   B   C   D   E   F   G
1  88  84  98  75  99  78  39
2  17  43  49  92  32   7   3
3  25  96   4  78  85  15   7
4  37  61  67  79   8  27  13
5  69   8  43  14  85  59  29

In [207]:
df1.drop('G',axis=1)

A   B   C   D   E   F
1  88  84  98  75  99  78
2  17  43  49  92  32   7
3  25  96   4  78  85  15
4  37  61  67  79   8  27
5  69   8  43  14  85  59

In [208]:
df1

A   B   C   D   E   F   G
1  88  84  98  75  99  78  39
2  17  43  49  92  32   7   3
3  25  96   4  78  85  15   7
4  37  61  67  79   8  27  13
5  69   8  43  14  85  59  29

In [209]:
df1.drop('G',axis=1,inplace=True)

In [210]:
df1

A   B   C   D   E   F
1  88  84  98  75  99  78
2  17  43  49  92  32   7
3  25  96   4  78  85  15
4  37  61  67  79   8  27
5  69   8  43  14  85  59

In [211]:
df.loc['A']

a1    79
b1    52
c1    16
d1    20
Name: A, dtype: int32

In [216]:
df.iloc[0]

a1    79
b1    52
c1    16
d1    20
Name: A, dtype: int32

In [217]:
df1

A   B   C   D   E   F
1  88  84  98  75  99  78
2  17  43  49  92  32   7
3  25  96   4  78  85  15
4  37  61  67  79   8  27
5  69   8  43  14  85  59

In [220]:
df1.loc['2']

A    17
B    43
C    49
D    92
E    32
F     7
Name: 2, dtype: int32

In [222]:
df1.iloc[1]

A    17
B    43
C    49
D    92
E    32
F     7
Name: 2, dtype: int32

In [223]:
df

a1  b1  c1  d1
A  79  52  16  20
B  96  35  43  58
C  26  89  21  95
D  99  43  11  94
E  90  87   4  29
F  95  42  28   3
G  99  93  17  47
H  92  24  89  43
I  73  58  40  63

In [224]:
df>0

a1    b1    c1    d1
A  True  True  True  True
B  True  True  True  True
C  True  True  True  True
D  True  True  True  True
E  True  True  True  True
F  True  True  True  True
G  True  True  True  True
H  True  True  True  True
I  True  True  True  True

In [225]:
df[df>0]

a1  b1  c1  d1
A  79  52  16  20
B  96  35  43  58
C  26  89  21  95
D  99  43  11  94
E  90  87   4  29
F  95  42  28   3
G  99  93  17  47
H  92  24  89  43
I  73  58  40  63

In [230]:
df[df['c1']>15]

a1  b1  c1  d1
A  79  52  16  20
B  96  35  43  58
C  26  89  21  95
F  95  42  28   3
G  99  93  17  47
H  92  24  89  43
I  73  58  40  63

In [233]:
df[df['c1']>50]['b1']

H    24
Name: b1, dtype: int32

In [234]:
df.reset_index()

index  a1  b1  c1  d1
0     A  79  52  16  20
1     B  96  35  43  58
2     C  26  89  21  95
3     D  99  43  11  94
4     E  90  87   4  29
5     F  95  42  28   3
6     G  99  93  17  47
7     H  92  24  89  43
8     I  73  58  40  63

In [235]:
newind = 'ID US MY KR AU GB JP CN PH'.split()

In [236]:
df['States'] = newind

In [237]:
df

a1  b1  c1  d1 States
A  79  52  16  20     ID
B  96  35  43  58     US
C  26  89  21  95     MY
D  99  43  11  94     KR
E  90  87   4  29     AU
F  95  42  28   3     GB
G  99  93  17  47     JP
H  92  24  89  43     CN
I  73  58  40  63     PH

In [238]:
df.set_index('States')

a1  b1  c1  d1
States                
ID      79  52  16  20
US      96  35  43  58
MY      26  89  21  95
KR      99  43  11  94
AU      90  87   4  29
GB      95  42  28   3
JP      99  93  17  47
CN      92  24  89  43
PH      73  58  40  63

In [239]:
df


a1  b1  c1  d1 States
A  79  52  16  20     ID
B  96  35  43  58     US
C  26  89  21  95     MY
D  99  43  11  94     KR
E  90  87   4  29     AU
F  95  42  28   3     GB
G  99  93  17  47     JP
H  92  24  89  43     CN
I  73  58  40  63     PH

In [240]:
df.set_index('States',inplace=True)

In [241]:
df

a1  b1  c1  d1
States                
ID      79  52  16  20
US      96  35  43  58
MY      26  89  21  95
KR      99  43  11  94
AU      90  87   4  29
GB      95  42  28   3
JP      99  93  17  47
CN      92  24  89  43
PH      73  58  40  63

In [242]:
outside = ['G1','G1','G1','G2','G2','G2']
inside = [1,2,3,1,2,3]
hier_index = list(zip(outside,inside))
hier_index = pd.MultiIndex.from_tuples(hier_index)

In [243]:
hier_index

MultiIndex(levels=[['G1', 'G2'], [1, 2, 3]],
           codes=[[0, 0, 0, 1, 1, 1], [0, 1, 2, 0, 1, 2]])

In [246]:
df2 =pd.DataFrame(np.random.randn(6,2),index=hier_index,columns=['A','B'])

In [247]:
df2

A         B
G1 1 -0.722115  0.895470
   2 -2.311053  1.156934
   3 -0.513615  1.309745
G2 1 -0.275208 -0.787765
   2  0.529723 -1.646292
   3 -1.026541  0.353339

In [248]:
df2.loc['G1']

A         B
1 -0.722115  0.895470
2 -2.311053  1.156934
3 -0.513615  1.309745

In [250]:
df2.loc['G1'].loc[1]

A   -0.722115
B    0.895470
Name: 1, dtype: float64

In [252]:
df2.index.names = ['Group','Num']

In [253]:
df2

A         B
Group Num                    
G1    1   -0.722115  0.895470
      2   -2.311053  1.156934
      3   -0.513615  1.309745
G2    1   -0.275208 -0.787765
      2    0.529723 -1.646292
      3   -1.026541  0.353339

In [254]:
df2.loc['G2']

A         B
Num                    
1   -0.275208 -0.787765
2    0.529723 -1.646292
3   -1.026541  0.353339

In [255]:
df2.loc['G2'].loc[2]['B']

-1.6462922650681295

In [256]:
df2.xs('G1')

A         B
Num                    
1   -0.722115  0.895470
2   -2.311053  1.156934
3   -0.513615  1.309745

In [257]:
df2.xs(['G1',1])

A   -0.722115
B    0.895470
Name: (G1, 1), dtype: float64

In [258]:
df2.xs(1,level='Num')

A         B
Group                    
G1    -0.722115  0.895470
G2    -0.275208 -0.787765